kind: ScaledObject
apiVersion: keda.sh/v1alpha1
metadata:
  name: nginx-app-http
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-app
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: prometheus
    metadata:
      serverAddress: http://prometheus-server.default.svc.cluster.local:80
      query: sum(rate(nginx_http_requests_total[1m]))
      threshold: "10"